### ISSUE TITLE
Backup PostgreSQL database to Azure Storage using pg_dump

### ISSUE THREAD

**Issue by ootneim** [Altinn/altinn-platform#490]
**Description:**
Implement a solution to backup a PostgreSQL database to an Azure Storage account using `pg_dump`. This will help ensure data resilience and facilitate easy restore in case of any data loss or corruption.

- [x] Set up a Linux VM or an appropriate environment for executing the backup process.
- [x] Install PostgreSQL and the necessary client tools, including `pg_dump`, on the VM.
- [x] Configure network access and security settings for the VM to allow connectivity to the PostgreSQL server.
- [x] Identify the connection details for the PostgreSQL Flexible Server, including the connection string and the target database name.
- [x] Create an Azure Storage account and container to store the database backups.
- [x] Install the Azure CLI on the Linux VM or the target environment.
- [x] Set up authentication and ensure that the Azure CLI has the necessary permissions to access the Azure Storage account.
- [x] Create a DevOps pipeline using a YAML file for automating the backup process.
- [x] Configure the pipeline to trigger on a schedule
- [x] Use `pg_dump` in the pipeline to create a backup file of the PostgreSQL database.
- [x] Use the Azure CLI in the pipeline to upload the backup file to the Azure Storage account and container.
- [x] Test the pipeline to ensure that the backup process is executed successfully.
- [x] Document the backup solution, including the pipeline configuration, backup schedule, and restore procedures.

**Additional Considerations:**
- Consider encrypting the backup file before uploading it to Azure Storage for enhanced security.
- Set up retention policies for the backups in the Azure Storage account to manage storage costs and comply with data retention requirements.
- Evaluate and implement appropriate backup rotation strategies based on your specific needs (e.g., incremental backups, full backups).

**Comment by ootneim** [comment]
Example yaml pipeline

```yaml
trigger:
  branches:
    include:
      - master

stages:
  - stage: Backup
    displayName: Backup PostgreSQL
    jobs:
      - job: BackupJob
        displayName: Backup Job
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: UsePythonVersion@0
            displayName: Use Python 3.x
            inputs:
              versionSpec: '3.x'

          - task: Bash@3
            displayName: Dump PostgreSQL Database
            inputs:
              targetType: 'inline'
              script: |
                # Replace <connection-string> with the actual connection string to your PostgreSQL Flexible Server
                # Replace <database-name> with the name of the database to back up
                pg_dump "<connection-string>" -d "<database-name>" -F c -f backup.dump
            workingDirectory: '/home/your-username'

          - task: AzureCLI@2
            displayName: Upload Backup to Azure Storage
            inputs:
              azureSubscription: 'YourAzureSubscription'  # Replace with the name of your Azure subscription service connection
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Replace <storage-account-name> with the name of your Azure Storage account
                # Replace <container-name> with the name of the container where you want to store the backup
                az storage blob upload --account-name "<storage-account-name>" --container-name "<container-name>" --name "backup.dump" --type block --file "/home/your-username/backup.dump"

```
