### ISSUE TITLE
Upgrade linkerd to 2.13.6 platform

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#554]
### Description

In 2.13.0-5, the default inbound and outbound HTTP request queue capacity decreased from 10,000 requests to 100 requests

Proxy
* Changed the default HTTP request queue capacities for the inbound and outbound proxies back to 10,000 requests (https://github.com/linkerd/linkerd2/issues/11198; fixes https://github.com/linkerd/linkerd2/issues/11055)

Platform should exclude proxy for outbound 443 for daemonset:
```yaml
spec:
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "443"
```

### Tasks

- [ ] Upgrade platform
- [ ] Upgrade apps
