### ISSUE TITLE
Consider adding kics.io to terraform pipelines

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#72]
Find security vulnerabilities, compliance issues, and infrastructure misconfigurations early in the development cycle of your infrastructure-as-code with KICS by Checkmarx.

KICS stands for Keeping Infrastructure as Code Secure, it is open source and is a must-have for any cloud native project.

Code solutions: Terraform, Kubernetes, Docker, AWS CloudFormation, Ansible, Helm, Google Deployment Manager, AWS SAM, Microsoft ARM, and OpenAPI 3.0 specifications.

By running kics on iac code you get a compliance report checked against best prctices. You can add your own compliance requirements to check againt.

**Comment by bengtfredh** [comment]
- [ ] Set up pipeline:
```
#
# Example using SARIF viewer:
# https://marketplace.visualstudio.com/items?itemName=sariftools.sarif-viewer-build-tab
#
trigger:
  - master
pool:
  vmImage: "ubuntu-latest"
container: checkmarx/kics:debian
steps:
  # run in CI mode, do not fail the pipeline on results found and export the report in both json and SARIF format.
  - script: |
      /app/bin/kics scan --ci -p ${PWD} -o ${PWD} --report-formats json,sarif --ignore-on-exit results
      cat results.json
  # scan results should be visible in the SARIF viewer tab of the build.
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(System.DefaultWorkingDirectory)/results.sarif
      artifactName: CodeAnalysisLogs
```

- [ ] Install this extension from marketplace [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=sariftools.sarif-viewer-build-tab).
