### ISSUE TITLE
Metrics server throttling in kubernetes

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#940]
### Description

We observe in several clusters that metrics-server is throttling and usage is not balanced between pods.

### Additional Information

Azure have recommendation for adjusting vpa to more sensible values.
https://learn.microsoft.com/en-us/azure/aks/use-metrics-server-vertical-pod-autoscaler

We hva applied the recommended solution in cluster that create alerts about metrics-server. Looks like this work good for our workflow.

### Tasks

deploy this configMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-server-config
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  NannyConfiguration: |-
    apiVersion: nannyconfig/v1alpha1
    kind: NannyConfiguration
    baseCPU: 100m
    cpuPerNode: 1m
    baseMemory: 100Mi
    memoryPerNode: 8Mi
```

```[tasklist]
### Deploymentplan
- [x] at_ring1
- [x] at_ring2
- [x] tt_ring1
- [x] tt_ring2
- [x] prod_ring1
- [x] prod_ring2
```
